// Auth
const USER_LOGIN = "USER_LOGIN";
const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
const USER_LOGIN_FAILED = "USER_LOGIN_FAILED";
const USER_LOGOUT = "USER_LOGOUT";
const USER_REGISTER = "USER_REGISTER";
const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
const USER_REGISTER_FAILED = "USER_REGISTER_FAILED";
const USER_LOGGED = "USER_LOGGED";
const CHANGE_PASSWORD = "CHANGE_PASSWORD";
const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
const CHANGE_PASSWORD_FAILED = "CHANGE_PASSWORD_FAILED";
const CHANGE_INFORMATION = "CHANGE_INFORMATION";
const CHANGE_INFORMATION_SUCCESS = "CHANGE_INFORMATION_SUCCESS";
const CHANGE_INFORMATION_FAILED = "CHANGE_INFORMATION_FAILED";
const GET_USER = "GET_USER";
const GET_USER_SUCCESS = "GET_USER_SUCCESS";
const GET_USER_FAILED = "GET_USER_FAILED";

// Product
const GET_ALL_PRODUCT = "GET_ALL_PRODUCT";
const GET_ALL_PRODUCT_SUCCESS = "GET_ALL_PRODUCT_SUCCESS";
const GET_ALL_PRODUCT_FAILED = "GET_ALL_PRODUCT_FAILED";
const GET_A_PRODUCT = "GET_A_PRODUCT";
const GET_A_PRODUCT_SUCCESS = "GET_A_PRODUCT_SUCCESS";
const GET_A_PRODUCT_FAILED = "GET_A_PRODUCT_FAILED";
const CREATE_PRODUCT = "CREATE_PRODUCT";
const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED";
const UPDATE_PRODUCT = "UPDATE_PRODUCT";
const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";
const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
const GET_PRODUCT_LIST_FAILED = "GET_PRODUCT_LIST_FAILED";
const RESET_PRODUCT_LIST = "RESET_PRODUCT_LIST";
const CREATE_REVIEW = "CREATE_REVIEW";
const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
const CREATE_REVIEW_FAILED = "CREATE_REVIEW_FAILED";
const GET_REVIEW = "GET_REVIEW";
const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
const GET_REVIEW_FAILED = "GET_REVIEW_FAILED";

// Checkout
const CHECKOUT = "CHECKOUT";
const CHECKOUT_SUCCESS = "CHECKOUT_SUCCESS";
const CHECKOUT_FAILED = "CHECKOUT";

// IMAGE PRODUCT
// const UPLOAD_IMAGE_PRODUCT = "UPLOAD_IMAGE_PRODUCT";
// const UPLOAD_IMAGE_PRODUCT_SUCCESS = "UPLOAD_IMAGE_PRODUCT_SUCCESS";
// const UPLOAD_IMAGE_PRODUCT_FAILED = "UPLOAD_IMAGE_PRODUCT_FAILED";
// const REMOVE_IMAGE_PRODUCT = "REMOVE_IMAGE_PRODUCT";
// const REMOVE_IMAGE_PRODUCT_SUCCESS = "REMOVE_IMAGE_PRODUCT_SUCCESS";
// const REMOVE_IMAGE_PRODUCT_FAILED = "REMOVE_IMAGE_PRODUCT_FAILED";

export {
    USER_LOGIN,
    USER_LOGIN_FAILED,
    USER_LOGIN_SUCCESS,
    USER_LOGOUT,
    USER_REGISTER,
    USER_REGISTER_SUCCESS,
    USER_REGISTER_FAILED,
    USER_LOGGED,
    CHANGE_PASSWORD,
    CHANGE_PASSWORD_SUCCESS,
    CHANGE_PASSWORD_FAILED,
    CHANGE_INFORMATION,
    CHANGE_INFORMATION_SUCCESS,
    CHANGE_INFORMATION_FAILED,
    GET_USER,
    GET_USER_SUCCESS,
    GET_USER_FAILED,
    GET_ALL_PRODUCT,
    GET_ALL_PRODUCT_SUCCESS,
    GET_ALL_PRODUCT_FAILED,
    GET_A_PRODUCT,
    GET_A_PRODUCT_SUCCESS,
    GET_A_PRODUCT_FAILED,
    CREATE_PRODUCT,
    CREATE_PRODUCT_SUCCESS,
    CREATE_PRODUCT_FAILED,
    UPDATE_PRODUCT,
    UPDATE_PRODUCT_SUCCESS,
    UPDATE_PRODUCT_FAILED,
    GET_PRODUCT_LIST,
    GET_PRODUCT_LIST_SUCCESS,
    GET_PRODUCT_LIST_FAILED,
    RESET_PRODUCT_LIST,
    CREATE_REVIEW,
    CREATE_REVIEW_SUCCESS,
    CREATE_REVIEW_FAILED,
    GET_REVIEW,
    GET_REVIEW_SUCCESS,
    GET_REVIEW_FAILED,
    CHECKOUT,
    CHECKOUT_SUCCESS,
    CHECKOUT_FAILED,
};
